package com.midrive.voice.router_compiler.utils;

public class Const {
    //Generate
    public static final String SEPARATOR = "_";
    public static final String PROJECT = "Router";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE! IT WAS AUTO GENERATED BY ROUTER.";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_PROVIDER = PROJECT + SEPARATOR + "Providers";
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Interceptors";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.midrive.voice.router_compiler";

    //Custom interface
    private static final String MAIN_PACKAGE = "com.midrive.voice.router_api";
    private static final String TEMPLATE_PACKAGE = ".template";
    private static final String SERVICE_PACKAGE = ".service";
    public static final String PROVIDER = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".Provider";
    public static final String PROVIDER_GROUP = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".ProviderGroup";
    public static final String ROUTE_GROUP = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".RouteGroup";
    public static final String ROUTE_ROOT = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".RouteRoot";
    public static final String INTERCEPTOR = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".Interceptor";
    public static final String INTERCEPTOR_GROUP = MAIN_PACKAGE + TEMPLATE_PACKAGE + ".InterceptorGroup";
    public static final String METHOD_LOAD = "load";
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String SERVICE = "android.app.Service";
    public static final String ANNO_TYPE_ROUTE = "com.midrive.voice.router_annotation.annotation.Route";
    public static final String ANNO_TYPE_INTERCEPTOR = "com.midrive.voice.router_annotation.annotation.Intercept";
    public static final String MODULE_NAME = "ROUTER_MODULE_NAME";
    public static final String ROUTER_SP_CACHE_KEY = "ROUTER_SP_CACHE";
}
